# Generated by Django 3.1.6 on 2021-03-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='product', max_length=50)),
                ('price', models.FloatField(default=500.0)),
                ('quantity', models.IntegerField(default=10)),
                ('image', models.ImageField(default='products/noimage.jpg', upload_to='products')),
                ('category', models.CharField(choices=[('CAKES', 'cake'), ('PASTRIES', 'pastry'), ('BREADS', 'bread'), ('SWEETS', 'sweet'), ('SNACKS', 'snacks')], default='cake', max_length=10)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
