# Generated by Django 3.1.6 on 2021-03-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CAKES', 'cake'), ('PASTRIES', 'pastry'), ('BREADS', 'bread'), ('SWEETS', 'sweet'), ('SNACKS', 'snack')], default='cake', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='products/noimage.jpg', height_field=256, upload_to='products', width_field=512),
        ),
    ]
